### ISSUE TITLE
**您好！從粗體 introducing 部分開始 我有疑問 謝謝！** In this study, we present a novel single image super resolution method by **introducing** dense skip connections in a very deep network.

### ISSUE THREAD

**Issue by h223449961** [AlexZou14/alexzou14.github.io#1]
super resolution methods can be significantly boosted by using deep convolutional neural networks. 
超分辨率領域中，使用深度卷積網路極大地增強了網路的效能
**您好！從粗體 introducing 部分開始 我有疑問 謝謝！**
In this study, we present a novel single image super resolution method by **introducing** dense skip connections in a very deep network.
提出密集跳躍連接方法
In the proposed network, the feature maps of each layer are propagated into all subsequent layers, providing an effective way to combine the low level features and high level features to boost the reconstruction performance.
In addition, the dense skip connections in the network enable short paths to be built directly from the output to each layer, alleviating the vanishing gradient problem of very deep networks.
Moreover, deconvolution layers are integrated into the network to learn the upsampling filters and to speedup the reconstruction process.
Further, the proposed method substantially reduces the number of parameters, enhancing the computational efficiency.
We evaluate the proposed method using images from four benchmark datasets and set a new state of the art.

**Comment by AlexZou14** [comment]
请问你看的是哪一篇论文，具体指清楚一些。
